admin-warps:
  gui:
    title: "Warps"
    format:
      - "c#######c"
      - "#wwwwwww#"
      - "#wwwwwww#"
      - "#wwwwwww#"
      - "#wwwwwww#"
      - "c##<#>##c"
    slots:
      '#':
        icon:
          material: lime_stained_glass_pane
          display-name: ''
      'c':
        icon:
          material: sunflower
          display-name: ''
      '>':
        icon:
          material: arrow
          display-name: "Next Page"
        fallback: '#'
      '<':
        icon:
          material: arrow
          display-name: "Previous Page"
        fallback: '#'

private-warps:
  gui:
    title: "Homes"
    format:
      - "c#######c"
      - "#wwwwwww#"
      - "#wwwwwww#"
      - "#wwwwwww#"
      - "#wwwwwww#"
      - "c##<#>##c"
    slots:
      '#':
        icon:
          material: lime_stained_glass_pane
          display-name: ''
      'c':
        icon:
          material: sunflower
          display-name: ''
      '>':
        icon:
          material: arrow
          display-name: "Next Page"
        fallback: '#'
      '<':
        icon:
          material: arrow
          display-name: "Previous Page"
        fallback: '#'

public-warps:
  gui:
    title: "Player Warps"
    format:
      - "c#######c"
      - "#wwwwwww#"
      - "#wwwwwww#"
      - "#wwwwwww#"
      - "#wwwwwww#"
      - "c##<#>##c"
    slots:
      '#':
        icon:
          material: lime_stained_glass_pane
          display-name: ''
      'c':
        icon:
          material: sunflower
          display-name: ''
      '>':
        icon:
          material: arrow
          display-name: "Next Page"
        fallback: '#'
      '<':
        icon:
          material: arrow
          display-name: "Previous Page"
        fallback: '#'